# Created by Crt Vavros, copyright © 2022 ZeroPass. All rights reserved.
name: dmrtd
description: Dart implementation of ICAO Doc 9303 MRTD, created by ZeroPass

version: 2.0.0

environment:
  sdk: ^3.6.0

dependency_overrides:
  pointycastle:
    git:
      url: https://github.com/privacybydesign/pc-dart.git
      ref: master

dependencies:
  archive: ^3.6.1
  collection: ^1.19.0
  convert: ^3.1.2
  crypto: ^3.0.6
  expandable: ^5.0.1
  fixnum: ^1.1.1
  flutter_nfc_kit: ^3.6.0-rc.6
    #git:
  #  url: https://github.com/ZeroPass/flutter_nfc_kit.git
  logging: ^1.3.0
  meta: ^1.15.0
  tripledes_nullsafety: ^1.0.3
  pointycastle:
    git:
      url: https://github.com/privacybydesign/pc-dart.git
      ref: master
  diffie_hellman: ^0.1.2
  logger: ^2.3.0
  mrz_parser: ^2.0.0
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.10.0+4
  google_mlkit_commons: ^0.11.0
  camera_platform_interface: ^2.2.2

dev_dependencies:
  flutter:      # needed for flutter_nfc_kit
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.5